development:
  adapter: postgresql
  encoding: utf8
  database: concerts_development
  host: localhost
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  encoding: utf8
  database: concerts_test
  host: localhost
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  encoding: utf8
  database: concerts_production
  pool: 5
  timeout: 5000
