default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: devise-auth_development

test:
  <<: *default
  database: devise-auth_test

production:
  <<: *default
  database: devise-auth_production
  username: devise-auth
  password: <%= ENV['VIDEO-GAMES_DATABASE_PASSWORD'] %>
