# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ae9d8a1e808c4346e40875ba4d3c4c548bfdad8c61d4c150daff3175d053447d19f65a451d9de70c00c750e2d6cf066aa6dfe337f3761c574256c06bb5c27759

test:
  secret_key_base: c713763d6b23f046e344d632daf13750ec2d652ef7c6a19ee4161ea94d277025dd447473c15eff15292926f3a56fe40a6a1199dfeccd6e4f6fcc6057535af95d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
